<?php

namespace Kartographer\Tag;

use Config;
use FormatJson;
use Kartographer\SpecialMap;
use MediaWiki\MainConfigNames;

/**
 * @license MIT
 */
class MapFrameAttributeGenerator {
	private const ALIGN_CLASSES = [
		'left' => 'floatleft',
		'center' => 'center',
		'right' => 'floatright',
	];

	/** @var MapTagArgumentValidator */
	private MapTagArgumentValidator $args;
	/** @var Config */
	private Config $config;
	/** @var string */
	private string $mapServer;
	/** @var string */
	public string $cssWidth;
	/** @var int */
	private int $staticWidth;
	/** @var int|float|string */
	public $staticLon;
	/** @var float|string */
	public $staticLat;
	/** @var int|string */
	public $staticZoom;
	/** @var bool */
	public bool $framed;

	/**
	 * @param MapTagArgumentValidator $args
	 * @param Config $config
	 */
	public function __construct( MapTagArgumentValidator $args, Config $config ) {
		$this->args = $args;
		$this->config = $config;
		$this->mapServer = $this->config->get( 'KartographerMapServer' );

		if ( $this->args->width === 'full' ) {
			$this->cssWidth = '100%';
			$this->staticWidth = 800;
		} else {
			$this->cssWidth = $this->args->width . 'px';
			$this->staticWidth = (int)$this->args->width;
		}

		if ( $this->args->lat !== null && $this->args->lon !== null ) {
			$this->staticLat = (float)$this->args->lat;
			$this->staticLon = (float)$this->args->lon;
		} else {
			$this->staticLat = 'a';
			$this->staticLon = 'a';
		}
		if ( $this->args->zoom !== null ) {
			$this->staticZoom = (int)$this->args->zoom;
		} else {
			$this->staticZoom = 'a';
		}
		$caption = (string)$this->args->text;
		$this->framed = $caption !== '' || !$this->args->frameless;
	}

	/**
	 * @return array
	 */
	public function prepareAttrs(): array {
		$attrs = [
			'class' => [ 'mw-kartographer-map' ],
			// We need dimensions for when there is no img (editpreview or no staticmap)
			// because an <img> element with permanent failing src has either:
			// - intrinsic dimensions of 0x0, when alt=''
			// - intrinsic dimensions of alt size
			'style' => "width: $this->cssWidth; height: {$this->args->height}px;",
			// Attributes starting with "data-mw" are banned from user content in Sanitizer;
			// we add such an attribute here (by default empty) so that its presence can be
			// checked later to guarantee that they were generated by Kartographer
			// Warning: This attribute is also checked in Wikibase and should be modified there as
			// well if necessary!
			'data-mw-kartographer' => '',
			'data-style' => $this->args->mapStyle,
			'data-width' => $this->args->width,
			'data-height' => $this->args->height,
		];

		if ( $this->args->zoom !== null ) {
			$attrs['data-zoom'] = $this->args->zoom;
		}

		if ( $this->args->lat !== null && $this->args->lon !== null ) {
			$attrs['data-lat'] = $this->args->lat;
			$attrs['data-lon'] = $this->args->lon;
		}

		if ( $this->args->specifiedLangCode !== null ) {
			$attrs['data-lang'] = $this->args->specifiedLangCode;
		}

		if ( $this->args->showGroups ) {
			$attrs['data-overlays'] = FormatJson::encode( $this->args->showGroups, false,
				FormatJson::ALL_OK );
		}

		$attrs['href'] = SpecialMap::link( $this->staticLat, $this->staticLon, $this->staticZoom,
			$this->args->resolvedLangCode );

		$containerClass = [ 'mw-kartographer-container' ];
		if ( $this->args->width === 'full' ) {
			$containerClass[] = 'mw-kartographer-full';
		}
		$attrs['containerClass'] = $containerClass;

		if ( !$this->framed ) {
			array_push( $attrs['class'], ...$containerClass );
			if ( isset( self::ALIGN_CLASSES[$this->args->align] ) ) {
				$attrs['class'][] = self::ALIGN_CLASSES[$this->args->align];
			}
		}
		return $attrs;
	}

	/**
	 * @param bool $isPreview
	 * @param string $pagetitle
	 * @param ?int $revisionId
	 * @return array
	 */
	public function prepareImgAttrs( bool $isPreview, string $pagetitle, ?int $revisionId ): array {
		$imgUrlParams = [
			'lang' => $this->args->resolvedLangCode,
		];
		if ( $this->args->showGroups && !$isPreview ) {
			// Groups are not available to the static map renderer
			// before the page was saved, can only be applied via JS
			$imgUrlParams += [
				'domain' => $this->config->get( 'KartographerMediaWikiInternalUrl' ) ??
					$this->config->get( MainConfigNames::ServerName ),
				'title' => $pagetitle,
				'revid' => $revisionId,
				'groups' => implode( ',', $this->args->showGroups ),
			];
		}
		$imgUrl = "{$this->mapServer}/img/{$this->args->mapStyle},$this->staticZoom,$this->staticLat," .
			"$this->staticLon,{$this->staticWidth}x{$this->args->height}";
		$imgAttrs = [
			'src' => "$imgUrl.png?" . wfArrayToCgi( $imgUrlParams ),
			'width' => $this->staticWidth,
			'height' => $this->args->height,
			'decoding' => 'async',
		];

		$srcSetScalesConfig = $this->config->get( 'KartographerSrcsetScales' );
		if ( $this->config->get( MainConfigNames::ResponsiveImages ) && $srcSetScalesConfig ) {
			// For now only support 2x, not 1.5. Saves some bytes...
			$srcSetScales = array_intersect( $srcSetScalesConfig, [ 2 ] );
			$srcSets = [];
			foreach ( $srcSetScales as $srcSetScale ) {
				$scaledImgUrl = "$imgUrl@{$srcSetScale}x.png?" . wfArrayToCgi( $imgUrlParams );
				$srcSets[] = "{$scaledImgUrl} {$srcSetScale}x";
			}
			$imgAttrs[ 'srcset' ] = implode( ', ', $srcSets );
		}

		return $imgAttrs;
	}
}
