<?php

namespace Kartographer\Tag;

use Kartographer\Special\SpecialMap;
use MediaWiki\Config\Config;
use MediaWiki\Json\FormatJson;
use MediaWiki\MainConfigNames;

/**
 * @license MIT
 */
class MapFrameAttributeGenerator {

	private const ALIGN_CLASSES = [
		'left' => 'floatleft',
		'center' => 'center',
		'right' => 'floatright',
	];

	private const THUMB_ALIGN_CLASSES = [
		'left' => 'tleft',
		'center' => 'tnone center',
		'right' => 'tright',
		'none' => 'tnone',
	];

	private MapTagArgumentValidator $args;
	private Config $config;
	public string $cssWidth;

	public function __construct( MapTagArgumentValidator $args, Config $config ) {
		$this->args = $args;
		$this->config = $config;

		if ( $this->args->width === 'full' ) {
			$this->cssWidth = '100%';
		} else {
			$this->cssWidth = $this->args->width . 'px';
		}
	}

	/**
	 * @return string[]
	 */
	private function getContainerClasses(): array {
		return [
			'mw-kartographer-container',
			...( $this->args->width === 'full' ? [ 'mw-kartographer-full' ] : [] ),
		];
	}

	/**
	 * @return string[]
	 */
	public function getThumbClasses(): array {
		return [
			...$this->getContainerClasses(),
			'thumb',
			self::THUMB_ALIGN_CLASSES[$this->args->align],
		];
	}

	public function prepareAttrs(): array {
		$attrs = [
			// T359082: Temporarily disable dark mode unless we have a better idea
			'class' => [ 'mw-kartographer-map', 'notheme' ],
			// We need dimensions for when there is no img (editpreview or no staticmap)
			// because an <img> element with permanent failing src has either:
			// - intrinsic dimensions of 0x0, when alt=''
			// - intrinsic dimensions of alt size
			'style' => "width: $this->cssWidth; height: {$this->args->height}px;",
			// Attributes starting with "data-mw" are banned from user content in Sanitizer;
			// we add such an attribute here (by default empty) so that its presence can be
			// checked later to guarantee that they were generated by Kartographer
			// Warning: This attribute is also checked in Wikibase and should be modified there as
			// well if necessary!
			'data-mw-kartographer' => 'mapframe',
			'data-style' => $this->args->mapStyle,
			'data-width' => $this->args->width,
			'data-height' => $this->args->height,
		];

		if ( $this->args->zoom !== null ) {
			$attrs['data-zoom'] = $this->args->zoom;
		}

		if ( $this->args->hasCoordinates() ) {
			$attrs['data-lat'] = $this->args->lat;
			$attrs['data-lon'] = $this->args->lon;
		}

		if ( $this->args->specifiedLangCode !== null ) {
			$attrs['data-lang'] = $this->args->specifiedLangCode;
		}

		if ( $this->args->showGroups ) {
			$attrs['data-overlays'] = FormatJson::encode( $this->args->showGroups, false,
				FormatJson::ALL_OK );
		}

		$attrs['href'] = SpecialMap::link( $this->args->lat, $this->args->lon, $this->args->zoom,
			$this->args->getLanguageCodeWithDefaultFallback() );

		if ( $this->args->frameless ) {
			$attrs['class'] = [
				...$attrs['class'],
				...$this->getContainerClasses(),
				...(array)( self::ALIGN_CLASSES[$this->args->align] ?? [] ),
			];
		}

		return $attrs;
	}

	/**
	 * @param bool $serverMayRenderOverlays If the map server should attempt to render GeoJSON
	 *  overlays via their group id
	 * @param string $pagetitle
	 * @param ?int $revisionId
	 * @return array
	 */
	public function prepareImgAttrs( bool $serverMayRenderOverlays, string $pagetitle, ?int $revisionId ): array {
		$mapServer = $this->config->get( 'KartographerMapServer' );
		$fullWidth = $this->config->get( 'KartographerStaticFullWidth' );
		$staticWidth = $this->args->width === 'full' ? $fullWidth : (int)$this->args->width;

		$imgUrlParams = [
			'lang' => $this->args->getLanguageCodeWithDefaultFallback(),
		];
		if ( $this->args->showGroups && $serverMayRenderOverlays ) {
			// Groups are not available to the static map renderer
			// before the page was saved, can only be applied via JS
			$imgUrlParams += self::getUrlAttrs( $this->config, $pagetitle, $revisionId, $this->args->showGroups );
		}

		$imgUrl = "$mapServer/img/{$this->args->mapStyle}," .
			( $this->args->zoom ?? 'a' ) . ',' .
			( $this->args->lat ?? 'a' ) . ',' .
			( $this->args->lon ?? 'a' ) .
			",{$staticWidth}x{$this->args->height}";

		$imgAttrs = [
			'src' => "$imgUrl.png?" . wfArrayToCgi( $imgUrlParams ),
			'width' => $staticWidth,
			'height' => $this->args->height,
			'decoding' => 'async',
		];

		$srcSet = $this->getSrcSet( $imgUrl, $imgUrlParams );
		if ( $srcSet ) {
			$imgAttrs['srcset'] = $srcSet;
		}

		if ( $this->args->alt !== '' ) {
			$imgAttrs['alt'] = $this->args->alt;
		}

		return $imgAttrs;
	}

	/**
	 * @param Config $config
	 * @param string $title
	 * @param int|null $revId
	 * @param array $groupId
	 * @return array
	 */
	public static function getUrlAttrs( Config $config, string $title, ?int $revId, array $groupId ): array {
		return [
			'domain' => $config->get( 'KartographerMediaWikiInternalUrl' ) ??
				$config->get( MainConfigNames::ServerName ),
			'title' => $title,
			'revid' => $revId,
			'groups' => implode( ',', $groupId )
		];
	}

	private function getSrcSet( string $imgUrl, array $imgUrlParams = [] ): ?string {
		$scales = $this->config->get( 'KartographerSrcsetScales' );
		if ( !$scales || !$this->config->get( MainConfigNames::ResponsiveImages ) ) {
			return null;
		}

		// For now only support 2x, not 1.5. Saves some bytes...
		$scales = array_intersect( $scales, [ 2 ] );
		$srcSets = [];
		foreach ( $scales as $scale ) {
			$scaledImgUrl = "$imgUrl@{$scale}x.png?" . wfArrayToCgi( $imgUrlParams );
			$srcSets[] = "$scaledImgUrl {$scale}x";
		}
		return implode( ', ', $srcSets ) ?: null;
	}
}
