<?php

namespace Kartographer\Tag;

use FormatJson;
use Kartographer\Special\SpecialMap;
use MediaWiki\Config\Config;
use stdClass;

/**
 * @license MIT
 */
class MapLinkAttributeGenerator {

	private MapTagArgumentValidator $args;
	private Config $config;
	private ?stdClass $markerProperties;

	public function __construct( MapTagArgumentValidator $args, Config $config, ?stdClass $markerProperties ) {
		$this->args = $args;
		$this->config = $config;
		$this->markerProperties = $markerProperties;
	}

	/**
	 * Prepare MapLink array of attributes to be passed to the Node element
	 * @return array
	 */
	public function prepareAttrs(): array {
		$attrs = [
			'class' => [ 'mw-kartographer-maplink' ],
			// Attributes starting with "data-mw" are banned from user content in Sanitizer;
			// we add such an attribute here (by default empty) so that its presence can be
			// checked later to guarantee that they were generated by Kartographer
			'data-mw-kartographer' => 'maplink',
			'data-style' => $this->args->mapStyle,
			'href' => SpecialMap::link(
					$this->args->lat,
					$this->args->lon,
					$this->args->zoom,
					$this->args->getLanguageCodeWithDefaultFallback()
				)
		];

		if ( $this->args->zoom !== null ) {
			$attrs['data-zoom'] = (string)$this->args->zoom;
		}

		if ( $this->args->hasCoordinates() ) {
			$attrs['data-lat'] = (string)$this->args->lat;
			$attrs['data-lon'] = (string)$this->args->lon;
		}

		if ( $this->args->specifiedLangCode !== null ) {
			$attrs['data-lang'] = $this->args->specifiedLangCode;
		}

		$style = $this->extractMarkerCss();
		if ( $style ) {
			$attrs['class'][] = 'mw-kartographer-autostyled';
			$attrs['style'] = $style;
		}

		if ( $this->args->cssClass !== '' ) {
			$attrs['class'][] = $this->args->cssClass;
		}

		if ( !$this->args->hasCoordinates() && $this->args->getTextWithFallback() === null ) {
			$attrs['class'][] = 'error';
		}

		if ( $this->args->showGroups ) {
			$attrs['data-overlays'] = FormatJson::encode( $this->args->showGroups, false,
				FormatJson::ALL_OK );
		}

		return $attrs;
	}

	/**
	 * Extracts CSS style to be used by the link from GeoJSON
	 * @return string
	 */
	private function extractMarkerCss(): string {
		if ( $this->config->get( 'KartographerUseMarkerStyle' )
			&& $this->markerProperties
			&& isset( $this->markerProperties->{'marker-color'} )
			// JsonSchema already validates this value for us, however this regex will also fail
			// if the color is invalid
			&& preg_match( '/^#?((?:[\da-f]{3}){1,2})$/i', $this->markerProperties->{'marker-color'}, $m )
		) {
			return "background: #{$m[1]};";
		}

		return '';
	}

}
